// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
	"github.com/labstack/echo"
	"go-ca-webapi/02_cleanarchitecture/adapter/controller"
	"go-ca-webapi/02_cleanarchitecture/adapter/gateway"
	"go-ca-webapi/02_cleanarchitecture/domain"
	"go-ca-webapi/02_cleanarchitecture/usecase"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func Initialize(dbConn *gorm.DB, e *echo.Echo) App {
	item := gateway.NewItem(dbConn)
	domainItem := domain.NewItem(item)
	usecaseItem := usecase.NewItem(domainItem)
	controllerItem := controller.NewItem(e, usecaseItem)
	app := NewApp(e, usecaseItem, controllerItem)
	return app
}

// wire.go:

var superSet = wire.NewSet(gateway.NewItem, controller.NewItem, domain.NewItem, usecase.NewItem, NewApp)
